version: '3.4'

services:
  default-api:
    image: ${REGISTRY:-}/default-api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/poc/renger-default-api/Dockerfile